# Generated by Django 4.2 on 2023-04-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description_short', models.TextField(max_length=200, verbose_name='Краткое описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
