# Generated by Django 4.2 on 2023-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Позиция'),
        ),
    ]
